drop table events cascade;
create table events (
        id			serial8	PRIMARY KEY,
        type			varchar(20),
        category		varchar(20),
        theme			varchar(50),
        title			varchar(100),
        description		text,
        tel			varchar(20),
        fax			varchar(20),
        mailaddress		varchar(50),
        webpage			varchar(100),
        startDateTime	 	date,
        endDateTime		date,
        alldayFlag		bool,
        limitOfApplications	int4,
        galleryId		int4,
        startPlace		varchar(100),
        startAddress		varchar(100),
        terminatePlace		varchar(100),
        terminateAddress	varchar(100),
        viaPlace		varchar(100),
        viaAddress		varchar(100),
        islandId		int4,
        meetingId		int4,
        priceName1		varchar(100),
        price1			money,
        priceName2		varchar(100),
        price2			money,
        priceCurrence		varchar(3),
        priceInfo		varchar(200),
        logoId			int4,
        publisherId		int4,
        orgnizationId		int4,
        sourceName		varchar(100),
        sourceUrl		varchar(100),
        anticipants		varchar(20),
        status			varchar(20)
);
