create table island (
    id              serial PRIMARY KEY,
    nickname        varchar(89),
    name            varchar(80),
    logoId          int4,
    description     text,
    category        varchar(20),
    mobilityType    varchar(20),
    realityType     varchar(20),
    ownershipType   varchar(20),
    ownerName       varchar(80),
    ownerId         int4,
    creatorId       int4,
    meetingId       int4,
    galleryId       int4,
    tel             varchar(20),
    fax             varchar(20),
    mailaddress     varchar(50),
    webpage         varchar(50),
    countryCode     varchar(2),
    countryName     varchar(30),
    state           varchar(30),
    city            varchar(30),
    postcode        varchar(20),
    thoroghfare     varchar(30),
    subthroghfare   varchar(30),
    buildingName    varchar(50),
    floorNumber     varchar(3),
    roomNumber      varchar(10),
    address1        varchar(100),
    address2        varchar(100),
    address3        varchar(100),
    latitude        float8,
    longitude       float8
);

